project_id = "uoemijylmpzggpnknmdw"

[functions.mark-attendance]
verify_jwt = false

[functions.create-admin]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.admin-reset-password]
verify_jwt = false

[functions.delete-user]
verify_jwt = false
